"""empty message

Revision ID: cd0c79efe7e6
Revises: adad00cf2282
Create Date: 2018-11-06 07:29:11.282552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0c79efe7e6'
down_revision = 'adad00cf2282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('time_close', table_name='items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('time_close', 'items', ['time_close'], unique=True)
    # ### end Alembic commands ###
